spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  task:
    fixedDelay: 1000
    name: devTask
management:
  security:
    enabled=false:
ftp:
  server:
    ip: 192.168.35.126
    port: 21
    user: foo
    pass: foo
    localPath: /Users/jacob/Downloads/cccc/
    fixedDelay: 5000
server:
  port: 12000
file:
  monitor:
    directory: /Users/jacob/workspace/workflow-demo/inputDir
    filter: .txt
    interval: 1

---
spring:
  profiles: prod
  task:
    fixedDelay: 1000
    name: devTask
